name: Docker Build and Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
          
    - name: Extract metadata for Docker
      id:   meta
      uses: docker/metadata-action@v3
      with:
          images: canembed/arm-environ

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  test:
    runs-on: ubuntu-latest
    container: canembed/arm-environ:master
    
    steps:
    
    - name: CMake version
      run: cmake --version
