name: Test Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  checkout:
    runs-on: ubuntu-latest
 
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      run: ls
      
  test:
    runs-on: ubuntu-latest
    container: canembed/arm-environ:master
     
    steps:
    - 
      run: cmake --version
    -
      run: ls -R /github
    
