name: Test Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

 test:
    runs-on: ubuntu-latest
    container: canembed/arm-environ:master
     
    steps:
    - 
      run: cmake --version
    -
      run: ls -R /github
    
© 2021 GitHub,
