name: Test Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  checkout:
    runs-on: ubuntu-latest
 
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      run: ls
      
  test:
    runs-on: ubuntu-latest
     
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      run: docker run --rm -i \
            -v ${PWD}:/workspace/source \
            -w /workspace/source \
            canembed/arm-environ:master cmake --version
    -
      run: docker run --rm -i \
            -v ${PWD}:/workspace/source \
            -w /workspace/source \
            canembed/arm-environ:master ls -R /github
    
