name: Test Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  Build:
    runs-on: ubuntu-latest
 
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: No-op
      run: ls
    - 
      name: Test (CMake)
      run: docker run --rm -i -v ${PWD}:/workspace canembed/arm-environ:master cmake --version
    -
      name: Test (Local files)
      run: docker run --rm -i -v ${PWD}:/workspace canembed/arm-environ:master ls -R /workspace
    -
      name: Test (Copy local file via shell)
      run: cp README.md old.md
    -
      name: Test (Copy local file via docker)
      run: docker run --rm -i -v ${PWD}:/workspace canembed/arm-environ:master cp /workspace/README.md /workspace/README.old
    -
      name: Publish
      run: ls
      
