name: Test Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  checkout:
    runs-on: ubuntu-latest
 
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

  build:
    needs: checkout
    runs-on: ubuntu-latest
     
    steps:
    - 
      name: No-op
      run: ls

  test:
    needs: build
    runs-on: ubuntu-latest
     
    steps:
    - 
      run: docker run --rm -i -v ${PWD}:/workspace canembed/arm-environ:master cmake --version
    -
      run: docker run --rm -i -v ${PWD}:/workspace canembed/arm-environ:master ls -R /workspace
    
  publish:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    -
      run: ls
      
